### ISSUE TITLE
File.basename bug when monkey-patch used

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#100]
```diff
BasenameTest

 FAIL (0.01s) :: test_it_creates_basename_correctly
File.basename regression 2.
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: ASCII-8BIT
-""
+"/"
/home/travis/build/danielpclark/faster_path/test/refinements/basename_test.rb:32:in `test_it_creates_basename_correctly'

 FAIL (0.00s) :: test_it_does_the_same_as_file_basename
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: ASCII-8BIT
-""
+"/"
/home/travis/build/danielpclark/faster_path/test/basename_test.rb:57:in `test_it_does_the_same_as_file_basename'
CleanpathAggressiveTest

 FAIL (0.00s) :: test_clean_aggressive_dosish_stuff
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: ASCII-8BIT
-"/.."
+"/"
/home/travis/build/danielpclark/faster_path/test/ripple_effects/cleanpath_aggressive_test.rb:54:in `test_clean_aggressive_dosish_stuff'

 FAIL (0.00s) :: test_clean_aggressive_defaults
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: ASCII-8BIT
-"/.."
+"/"
/home/travis/build/danielpclark/faster_path/test/ripple_effects/cleanpath_aggressive_test.rb:20:in `test_clean_aggressive_defaults'

 FAIL (0.00s) :: test_clean_aggresive_defaults
Expected: "/.."
Actual: "/"
/home/travis/build/danielpclark/faster_path/test/ripple_effects/plus_test.rb:32:in `test_clean_aggresive_defaults'
CleanpathConservativeTest

 FAIL (0.00s) :: test_clean_conservative_defaults
--- expected
+++ actual
@@ -1,2 +1 @@
-# encoding: ASCII-8BIT
-"/.."
+"/"
/home/travis/build/danielpclark/faster_path/test/ripple_effects/cleanpath_conservative_test.rb:20:in `test_clean_conservative_defaults'
```

**Comment by danielpclark** [comment]
Could be a test suite bug.

**Comment by danielpclark** [comment]
I think this is actually a wrong implementation.  May need to rewrite.  For now it's marked as volatile with the unstable `WITH_REGRESSION` env flag.

**Comment by danielpclark** [comment]
Fixed.  Edge case added to rust code for any group of forward slashes.
