### ISSUE TITLE
undefined method `absolute?'

### ISSUE THREAD

**Issue by grosser** [danielpclark/faster_path#17]
using the sledgehammer on a 2.2.3p173 ruby app for osx ... did not work ...

```
# config/boot.rb
require "faster_path/optional/monkeypatches"
FasterPath.sledgehammer_everything!
```

```
faster_path-0.0.9/lib/faster_path/optional/monkeypatches.rb:5:in `absolute?': undefined method `absolute?' for FasterPath:Module (NoMethodError)
lib/ruby/2.2.0/pathname.rb:398:in `join'
config/application.rb:12:in
```

**Comment by grosser** [comment]
adding `require 'faster_path'` gets me to a new error:

```
bundle/ruby/2.2.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'vendor/bundle/ruby/2.2.0/gems/faster_path-0.0.9/target/release/libfaster_path.dylib': 
```

which I guess is rust missing ... but would be great if that failed at install time or have a nicer error message

**Comment by danielpclark** [comment]
Ah.  You're in OS X.  Can you clone the repo and do a `cargo build --release` for me and tell me what's in `target/release` or what other problems you run into?

**Comment by danielpclark** [comment]
I'm thinking I can add a `dylib` option to my `Cargo.toml` file if it's not being built in the Mac OS.  So let me know what you find.

**Comment by grosser** [comment]
```
ls target/release/
build                deps                 examples             libfaster_path.dylib native
```

**Comment by grosser** [comment]
works when I run `cargo build --release` in vendor/bundle/ruby/2.2.0/gems/faster_path-0.0.9 ...

**Comment by danielpclark** [comment]
Alright, thanks!  I've added Mac support.  I was removing all non `so,dll` files before so now I've added `dylib`.  I'm going to build another release version.

**Comment by grosser** [comment]
tried using it here ... no speedup to be found :(
https://github.com/zendesk/samson/pull/1068

**Comment by danielpclark** [comment]
[0.1.0](https://github.com/danielpclark/faster_path/tree/v0.1.0) released.  Can you use the derailed memory stack profiler for the speed test?

**Comment by danielpclark** [comment]
Mine would load the site 100 times in 31 seconds before hand, and only 11 after using the monkeypatch from this gem.  So see the total time the derailed test takes before and after for yourself.

**Comment by grosser** [comment]
can you give me the command I should run, readme for derailed is pretty long :D

**Comment by danielpclark** [comment]
Since my development environment is different I usually do

    RAILS_ENV=development bundle exec derailed exec perf:stackprof

**Comment by danielpclark** [comment]
I wonder if your Gemfile loads before config boot?  In my application it put this code in `config/initializers/faster_path.rb` .  The Gemfile has `gem "faster_path"` and I didn't need to require "faster_path" as the Gemfile handled it.

**Comment by grosser** [comment]
Gemfile does not handle it, `Bundler.require` in config/application.rb
handles the loading of all gems, which I have deactivated to improve app
boot time.

**Comment by grosser** [comment]
with:

```
==================================
  Mode: cpu(1000)
  Samples: 1139 (61.82% miss rate)
  GC: 110 (9.66%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       120  (10.5%)         120  (10.5%)     block in ActiveSupport::FileUpdateChecker#max_mtime
       104   (9.1%)         104   (9.1%)     block in Logger::LogDevice#write
       123  (10.8%)         101   (8.9%)     ActiveSupport::FileUpdateChecker#watched
       199  (17.5%)          90   (7.9%)     block in ActiveRecord::Migrator.migrations
        64   (5.6%)          64   (5.6%)     Time#compare_with_coercion
        88   (7.7%)          44   (3.9%)     ActiveSupport::Inflector#camelize
        41   (3.6%)          41   (3.6%)     ActiveRecord::ConnectionAdapters::Mysql2Adapter#active?
        30   (2.6%)          30   (2.6%)     block in BetterErrors::ExceptionExtension#set_backtrace
        28   (2.5%)          28   (2.5%)     block in ActiveSupport::Dependencies#loadable_constants_for_path
        29   (2.5%)          25   (2.2%)     ActiveSupport::Inflector#inflections
        41   (3.6%)          25   (2.2%)     block (2 levels) in BindingOfCaller::BindingExtensions#callers
        22   (1.9%)          22   (1.9%)     ActiveRecord::MigrationProxy#mtime
        22   (1.9%)          22   (1.9%)     block in ActiveSupport::FileUpdateChecker#watched
        22   (1.9%)          22   (1.9%)     ActiveRecord::MigrationProxy#initialize
        16   (1.4%)          16   (1.4%)     Statsd#send_to_socket
        18   (1.6%)          15   (1.3%)     block in ActiveSupport::Inflector#camelize
        12   (1.1%)          12   (1.1%)     block in ActionDispatch::FileHandler#match?
        12   (1.1%)          11   (1.0%)     Hashie::Mash#custom_writer
       128  (11.2%)          10   (0.9%)     block in ActiveSupport::Dependencies#load_file
         9   (0.8%)           9   (0.8%)     block in ActiveSupport::Dependencies#search_for_file
        27   (2.4%)           7   (0.6%)     Hashie::Mash#initialize
         7   (0.6%)           7   (0.6%)     Rack::MiniProfiler::TimerStruct::Base#initialize
         7   (0.6%)           7   (0.6%)     ActionDispatch::Journey::Visitors::Each#initialize
         6   (0.5%)           6   (0.5%)     ThreadSafe::NonConcurrentCacheBackend#[]
         7   (0.6%)           6   (0.5%)     ActiveRecord::ConnectionAdapters::DatabaseStatements#reset_transaction
         7   (0.6%)           5   (0.4%)     block in Module#delegate
         5   (0.4%)           5   (0.4%)     block (2 levels) in ActiveSupport::Dependencies::WatchStack#new_constants
         4   (0.4%)           4   (0.4%)     block in ActionDispatch::Journey::GTG::Builder#build_followpos
         4   (0.4%)           4   (0.4%)     block (2 levels) in <class:Numeric>
         6   (0.5%)           4   (0.4%)     ActionView::Context#_prepare_context
```

without:

```
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       128  (11.3%)         128  (11.3%)     block in ActiveSupport::FileUpdateChecker#max_mtime
       124  (11.0%)         124  (11.0%)     block in Logger::LogDevice#write
       113  (10.0%)         100   (8.9%)     ActiveSupport::FileUpdateChecker#watched
       192  (17.0%)          78   (6.9%)     block in ActiveRecord::Migrator.migrations
        62   (5.5%)          62   (5.5%)     Time#compare_with_coercion
        91   (8.1%)          51   (4.5%)     ActiveSupport::Inflector#camelize
        43   (3.8%)          43   (3.8%)     ActiveRecord::ConnectionAdapters::Mysql2Adapter#active?
        41   (3.6%)          41   (3.6%)     ActiveRecord::MigrationProxy#mtime
        40   (3.5%)          24   (2.1%)     block (2 levels) in BindingOfCaller::BindingExtensions#callers
        24   (2.1%)          24   (2.1%)     block in BetterErrors::ExceptionExtension#set_backtrace
        23   (2.0%)          23   (2.0%)     ActiveRecord::MigrationProxy#initialize
        19   (1.7%)          19   (1.7%)     Statsd#send_to_socket
        19   (1.7%)          16   (1.4%)     block in ActiveSupport::Inflector#camelize
        16   (1.4%)          16   (1.4%)     block in ActionDispatch::FileHandler#match?
        16   (1.4%)          16   (1.4%)     block in ActiveSupport::Dependencies#loadable_constants_for_path
        22   (1.9%)          15   (1.3%)     ActiveSupport::Inflector#inflections
        13   (1.2%)          13   (1.2%)     block in ActiveSupport::FileUpdateChecker#watched
         8   (0.7%)           8   (0.7%)     Rack::MiniProfiler::TimerStruct::Base#initialize
         8   (0.7%)           8   (0.7%)     ThreadSafe::NonConcurrentCacheBackend#[]
         7   (0.6%)           7   (0.6%)     block in ActiveSupport::Dependencies#search_for_file
        97   (8.6%)           6   (0.5%)     block in ActiveSupport::Dependencies#load_file
         5   (0.4%)           5   (0.4%)     Rack::Utils::HeaderHash#[]=
         6   (0.5%)           4   (0.4%)     block in Module#delegate
         6   (0.5%)           4   (0.4%)     ActiveRecord::ConnectionAdapters::Quoting#_quote
         4   (0.4%)           4   (0.4%)     Rack::BodyProxy#initialize
         5   (0.4%)           4   (0.4%)     Rack::Utils#parse_nested_query
         9   (0.8%)           3   (0.3%)     Hashie::Mash#initialize
         5   (0.4%)           3   (0.3%)     Rack::MockRequest.env_for
         3   (0.3%)           3   (0.3%)     Hashie::Mash#custom_writer
        25   (2.2%)           3   (0.3%)     ActionView::Renderer#render_template
```

**Comment by grosser** [comment]
also the gem advertises to improve boottime ... and derailed has very little to do with boot time ...

**Comment by danielpclark** [comment]
It advertises load time, not boot time.  Here's the difference it makes for me.

# before

```
Booting: development
Endpoint: "/"
       user     system      total        real
100 requests 30.530000   1.780000  32.310000 ( 32.509564)
Running `stackprof tmp/2016-06-13T07:02:21-04:00-stackprof-cpu-myapp.dump`. Execute `stackprof --help` for more info
==================================
  Mode: cpu(1000)
  Samples: 8114 (0.01% miss rate)
  GC: 978 (12.05%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      2334  (28.8%)        2334  (28.8%)     Pathname#chop_basename
      1218  (15.0%)        1036  (12.8%)     Hike::Index#entries
      1308  (16.1%)         432   (5.3%)     BetterErrors::ExceptionExtension#set_backtrace
       419   (5.2%)         416   (5.1%)     Sprockets::Mime#mime_types
      1749  (21.6%)         345   (4.3%)     Pathname#plus
      1338  (16.5%)         277   (3.4%)     BindingOfCaller::BindingExtensions#callers
       462   (5.7%)         238   (2.9%)     Hike::Index#find_aliases_for
       466   (5.7%)         234   (2.9%)     Hike::Index#sort_matches
      1976  (24.4%)         227   (2.8%)     Pathname#+
      1992  (24.6%)         133   (1.6%)     Hike::Index#match
       264   (3.3%)         132   (1.6%)     ActionView::PathResolver#find_template_paths
       236   (2.9%)         126   (1.6%)     Hike::Index#pattern_for
       121   (1.5%)         104   (1.3%)     Hike::Index#build_pattern_for
        90   (1.1%)          90   (1.1%)     Hike::Trail#stat
      2980  (36.7%)          67   (0.8%)     Pathname#join
        64   (0.8%)          59   (0.7%)     ActiveSupport::FileUpdateChecker#watched
        58   (0.7%)          58   (0.7%)     Time#compare_with_coercion
       106   (1.3%)          57   (0.7%)     Hike::Index#initialize
      6234  (76.8%)          57   (0.7%)     Sprockets::Rails::Helper#check_errors_for
       943  (11.6%)          38   (0.5%)     Pathname#relative?
        48   (0.6%)          29   (0.4%)     Sprockets::Engines#deep_copy_hash
        28   (0.3%)          28   (0.3%)     ActiveSupport::SafeBuffer#initialize
       136   (1.7%)          25   (0.3%)     ActiveSupport::FileUpdateChecker#max_mtime
        25   (0.3%)          25   (0.3%)     ActionView::Helpers::AssetUrlHelper#compute_asset_extname
        44   (0.5%)          24   (0.3%)     ActiveSupport::Inflector#camelize
       111   (1.4%)          20   (0.2%)     Sprockets::Asset#dependency_fresh?
       124   (1.5%)          20   (0.2%)     ActionView::Helpers::AssetUrlHelper#asset_path
        19   (0.2%)          19   (0.2%)     String#blank?
        16   (0.2%)          16   (0.2%)     Sprockets::Base#cache_key_for
     10487 (129.2%)          15   (0.2%)     Sprockets::Base#resolve
```

# after

```
Booting: development
Endpoint: "/"
       user     system      total        real
100 requests 10.990000   0.590000  11.580000 ( 11.687753)
Running `stackprof tmp/2016-06-13T18:10:34-04:00-stackprof-cpu-myapp.dump`. Execute `stackprof --help` for more info
==================================
  Mode: cpu(1000)
  Samples: 2910 (0.00% miss rate)
  GC: 329 (11.31%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       500  (17.2%)         500  (17.2%)     #<Module:0x0000000452a450>.chop_basename
       850  (29.2%)         206   (7.1%)     Hike::Index#match
       630  (21.6%)         199   (6.8%)     BetterErrors::ExceptionExtension#set_backtrace
       680  (23.4%)         179   (6.2%)     Pathname#plus
       698  (24.0%)         154   (5.3%)     BindingOfCaller::BindingExtensions#callers
       155   (5.3%)         146   (5.0%)     Hike::Index#entries
       242   (8.3%)         121   (4.2%)     ActionView::PathResolver#find_template_paths
       795  (27.3%)         115   (4.0%)     Pathname#+
       198   (6.8%)         101   (3.5%)     Hike::Index#find_aliases_for
       189   (6.5%)          94   (3.2%)     Hike::Index#sort_matches
        93   (3.2%)          92   (3.2%)     Sprockets::Mime#mime_types
       107   (3.7%)          53   (1.8%)     Hike::Index#pattern_for
        58   (2.0%)          52   (1.8%)     ActiveSupport::FileUpdateChecker#watched
        49   (1.7%)          49   (1.7%)     Time#compare_with_coercion
        59   (2.0%)          48   (1.6%)     Hike::Index#build_pattern_for
        46   (1.6%)          46   (1.6%)     #<Module:0x0000000452a450>.absolute?
       880  (30.2%)          39   (1.3%)     Pathname#join
       140   (4.8%)          32   (1.1%)     ActiveSupport::FileUpdateChecker#max_mtime
        31   (1.1%)          16   (0.5%)     Hike::Index#initialize
        27   (0.9%)          16   (0.5%)     ActiveSupport::Inflector#camelize
      3061 (105.2%)          13   (0.4%)     Hike::Index#find
        68   (2.3%)          11   (0.4%)     ActiveRecord::Migrator.migrations
        27   (0.9%)           9   (0.3%)     ActiveSupport::Dependencies::Loadable#require
         8   (0.3%)           8   (0.3%)     ThreadSafe::NonConcurrentCacheBackend#[]
         8   (0.3%)           8   (0.3%)     Hashie::Mash#convert_key
         8   (0.3%)           8   (0.3%)     Rack::MiniProfiler.config
        40   (1.4%)           8   (0.3%)     Rack::MiniProfiler::TimerStruct::Sql#initialize
      3026 (104.0%)           7   (0.2%)     Hike::Index#find_in_paths
         7   (0.2%)           7   (0.2%)     String#blank?
        28   (1.0%)           5   (0.2%)     Sprockets::AssetAttributes#search_paths
danielpclark@allyourdev:~/dev/fast/tagfer-daniel$ less config/initializers/faster_path.rb 
```

As you can see I addressed the method my application hit the most and the site improved load time by 66%.

I'm using Sprockets version 2.12.4 which has more `Pathname` usage and uses the Hike gem as well which also uses `Pathname`.

**Comment by danielpclark** [comment]
Do you know why you're having a `Samples: 1139 (61.82% miss rate)`?  I'm not having misses in my derailed checks.

**Comment by grosser** [comment]
Not sure, maybe because the action was too fast ... I gutted a bunch of things to make it not require a logged in user ... results with full page / logged in user:

```
100 requests 38.750000   6.400000  45.150000 ( 62.857037)
Running `stackprof tmp/2016-06-14T01:58:08+00:00-stackprof-cpu-myapp.dump`. Execute `stackprof --help` for more info
==================================
  Mode: cpu(1000)
  Samples: 31096 (8.82% miss rate)
  GC: 2245 (7.22%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
     10202  (32.8%)       10202  (32.8%)     Sprockets::PathUtils#stat
      2293   (7.4%)        2293   (7.4%)     block in Mysql2::Client#query
      2774   (8.9%)        1737   (5.6%)     ActionView::PathResolver#find_template_paths
      6122  (19.7%)        1395   (4.5%)     ActiveRecord::ConnectionAdapters::Mysql2Adapter#exec_query
      1303   (4.2%)        1303   (4.2%)     Rack::MiniProfiler.config
      1149   (3.7%)        1149   (3.7%)     block in Logger::LogDevice#write
      1037   (3.3%)        1037   (3.3%)     block in ActionView::PathResolver#find_template_paths
       646   (2.1%)         646   (2.1%)     block (2 levels) in Rack::MiniProfiler::TimerStruct::Sql#initialize
       978   (3.1%)         601   (1.9%)     Sprockets::URITar#initialize
       983   (3.2%)         541   (1.7%)     Sprockets::Cache::FileStore#safe_open
       545   (1.8%)         421   (1.4%)     Sprockets::URITar#expand
       377   (1.2%)         377   (1.2%)     Sprockets::Paths#root
      1042   (3.4%)         306   (1.0%)     block in #<Module:0x007f9c4d9b0f28>.render_javascripts
       288   (0.9%)         288   (0.9%)     URI::RFC3986_Parser#split
       278   (0.9%)         273   (0.9%)     Sprockets::PathUtils#entries
       216   (0.7%)         216   (0.7%)     #<Module:0x007f9c4c0cbad0>.load_with_autoloading
       532   (1.7%)         181   (0.6%)     block in #<Module:0x007f9c4d9b0f28>.render_stylesheets
       390   (1.3%)         174   (0.6%)     Sprockets::EncodingUtils#unmarshaled_deflated
       163   (0.5%)         163   (0.5%)     rescue in Dalli::Server::KSocket::InstanceMethods#readfull
       153   (0.5%)         153   (0.5%)     block (4 levels) in Sprockets::Mime#compute_extname_map
       172   (0.6%)         146   (0.5%)     block in ActionView::PathResolver#query
       128   (0.4%)         128   (0.4%)     block in ActiveSupport::FileUpdateChecker#max_mtime
       119   (0.4%)         119   (0.4%)     Sprockets::PathUtils#absolute_path?
       112   (0.4%)         112   (0.4%)     ActiveSupport::PerThreadRegistry#instance
       111   (0.4%)         110   (0.4%)     Set#add
       110   (0.4%)         110   (0.4%)     block in BetterErrors::ExceptionExtension#set_backtrace
       101   (0.3%)         101   (0.3%)     Set#replace
       134   (0.4%)         100   (0.3%)     ActiveSupport::FileUpdateChecker#watched
        78   (0.3%)          78   (0.3%)     ThreadSafe::NonConcurrentCacheBackend#[]
        78   (0.3%)          75   (0.2%)     Sprockets::DigestUtils#digest
```

and with `config.assets.compile = false`

```
      2472  (12.2%)        2472  (12.2%)     Rack::MiniProfiler.config
      2167  (10.7%)        2167  (10.7%)     block in Mysql2::Client#query
      3118  (15.4%)        1967   (9.7%)     ActionView::PathResolver#find_template_paths
      1300   (6.4%)        1300   (6.4%)     block in Logger::LogDevice#write
      7696  (37.9%)        1228   (6.0%)     ActiveRecord::ConnectionAdapters::Mysql2Adapter#exec_query
      1151   (5.7%)        1151   (5.7%)     block in ActionView::PathResolver#find_template_paths
      1048   (5.2%)        1048   (5.2%)     block (2 levels) in Rack::MiniProfiler::TimerStruct::Sql#initialize
       286   (1.4%)         248   (1.2%)     block in ActionView::PathResolver#query
       192   (0.9%)         191   (0.9%)     ActiveSupport::PerThreadRegistry#instance
       222   (1.1%)         191   (0.9%)     block in #<Module:0x007f9e659ca4e0>.render_javascripts
       216   (1.1%)         177   (0.9%)     block in #<Module:0x007f9e659ca4e0>.render_stylesheets
       168   (0.8%)         168   (0.8%)     block in ActiveSupport::FileUpdateChecker#max_mtime
       142   (0.7%)         142   (0.7%)     ThreadSafe::NonConcurrentCacheBackend#[]
       136   (0.7%)         136   (0.7%)     block in BetterErrors::ExceptionExtension#set_backtrace
       133   (0.7%)         133   (0.7%)     rescue in Dalli::Server::KSocket::InstanceMethods#readfull
       166   (0.8%)         126   (0.6%)     Arel::Nodes::Binary#hash
       111   (0.5%)         111   (0.5%)     block (4 levels) in Class#class_attribute
       225   (1.1%)         105   (0.5%)     block in ActiveRecord::Migrator.migrations
       155   (0.8%)         103   (0.5%)     ActiveRecord::Relation#initialize_copy
       101   (0.5%)         101   (0.5%)     Time#compare_with_coercion
       128   (0.6%)         101   (0.5%)     ActiveSupport::FileUpdateChecker#watched
       163   (0.8%)          91   (0.4%)     block (2 levels) in BindingOfCaller::BindingExtensions#callers
        79   (0.4%)          79   (0.4%)     block in ActiveSupport::Dependencies#loadable_constants_for_path
        76   (0.4%)          74   (0.4%)     block in ActiveRecord::QueryMethods#validate_order_args
        74   (0.4%)          74   (0.4%)     block in ActiveSupport::Inflector#apply_inflections
       223   (1.1%)          72   (0.4%)     ActiveModel::AttributeMethods::ClassMethods#attribute_alias?
        68   (0.3%)          68   (0.3%)     ActiveRecord::Inheritance::ClassMethods#base_class
        65   (0.3%)          65   (0.3%)     block (2 levels) in <class:Numeric>
        61   (0.3%)          61   (0.3%)     Arel::Collectors::Bind#<<
       186   (0.9%)          58   (0.3%)     ActiveRecord::QueryMethods#preprocess_order_args
```

**Comment by danielpclark** [comment]
I see you're using the Sprockets ~> 3.0 series.  When I tried upgrading to that it slowed my site down by roughly 20% . see: https://github.com/rails/sprockets/issues/84#issuecomment-223742047

I'm not sure how much Sprockets depends on the STDLIB Pathname class anymore.  I'll look into it.

**Comment by danielpclark** [comment]
Yep.  As of Sprockets 3.0 series they've dropped most of their use of `Pathname`.  See: https://github.com/rails/sprockets/blob/master/lib/sprockets/path_utils.rb

They only require `Pathname` is an ALT separator is used and then only use the `Pathname#absolute?` method.

I don't think you'll see any performance gain unless you downgrade your Sprockets version, or until we add more methods that the newer Sprockets depends on.

**Comment by danielpclark** [comment]
Hey @grosser , I did more research into Sprockets.  _I've written all the details in the README._  After my research I believe your website can gain around 31% faster page load time by downgrading to Sprocket 2.0 series.  And then you may get an additional 30% by using this gem.  This result will be more clearly seen on your logged in user derailed profile results.  I'm basing these numbers off of my own website though so the data for you will likely vary.
