### ISSUE TITLE
Anyone have experience with pointers?

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#82]
See: [branch/chop_basename_pure](https://github.com/danielpclark/faster_path/tree/chop_basename_pure)

I'm working on re-implementing `FasterPath.chop_basename` in pure Rust and I'm following the instructions on [FFI returning an array of strings](https://github.com/ffi/ffi/wiki/Examples#array-of-strings) .  The detail on the pointer value is vague and I can't seem to find any documentation specific to Rust and Ruby for writing from Rust to Ruby via the memory pointer Ruby passed it.  I sort of have my best guess implementation at the moment but I'm getting the following FFI error in Ruby:

```
IndexError: Memory access offset=0 size=16 is out of bounds
    faster_path/lib/faster_path.rb:45:in `get_array_of_string'
    faster_path/lib/faster_path.rb:45:in `chop_basename'
```

**Comment by danielpclark** [comment]
* [FFI MemoryPointer Spec](https://github.com/ffi/ffi/blob/ce0e712bcb8876620e10c892d0b9005c84d92b53/spec/ffi/rbx/memory_pointer_spec.rb)
* [FFI MemoryPointer C code](https://github.com/ffi/ffi/blob/ce0e712bcb8876620e10c892d0b9005c84d92b53/ext/ffi_c/MemoryPointer.c)
* [FFI pointer read & write](https://github.com/ffi/ffi/blob/ce0e712bcb8876620e10c892d0b9005c84d92b53/lib/ffi/pointer.rb)
